server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: discovery-eureka-server
    
---
# Eureka instance 1 when used on Docker
spring:
  profiles: docker1
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/,http://discovery2:8762/eureka/

---
# Eureka instance 2 when used on Docker
spring:
  profiles: docker2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/,http://discovery2:8762/eureka/